### ISSUE TITLE
Github URL in form "url = https://{username}@github.com/{username}/{repo-name}.git not working

### ISSUE THREAD

**Issue by AriesMOo** [HookyQR/VSCodeGitHubIssues#10]
Similar to #9 it does not work with remote repos expresed in this way.. ;)

**Comment by HookyQR** [comment]
@AriesMOo upgrade to 0.1.2 and let me know how it goes.

**Comment by AriesMOo** [comment]
I think this was the version I had y my vs code :8ball:

**Comment by HookyQR** [comment]
@AriesMOo it's been a while, just wondering if this is still an issue for you.

**Comment by AriesMOo** [comment]
@HookyQR Sorry !! I didn't see the post on time.. In the end, I think it was caused by the HTTP proxy of my office and a bit of confussion with projects with/without public github repo. 
Tested outside with public repos, and works fine right now, so i think this issue can be closed.

Thanks for your (great) work ;)
