### ISSUE TITLE
Github URL with username/password 

### ISSUE THREAD

**Issue by tinovyatkin** [HookyQR/VSCodeGitHubIssues#9]
It seems that it doesn't recognize remotes with https://user:pass@github.com as Github repos

**Comment by HookyQR** [comment]
Can you please check if [this release](https://github.com/HookyQR/VSCodeGitHubIssues/releases/download/v0.1.1/GitHubIssues-0.1.1.vsix) works. You can drag and drop the downloaded file onto the VSCode workspace (anywhere except the the sidebar) to install it.

**Comment by tinovyatkin** [comment]
@HookyQR it works now, great!
